config/routes.rb
Rails.application.routes.draw do
devise_for :users
resources :postulants
resources :offers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  get '/offer', to: 'offers#new'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
      #relations
      has_many :postulants
      belongs_to :user
      
end

app/models/postulant.rb
class Postulant < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/user.rb
class User < ApplicationRecord
      # Include default devise modules. Others available are:
      # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
      devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

      has_one_attached :image
      # Relations
      has_many :offers
      has_many :postulants
  

  #enums
  enum:role,[:normal_user,:author,:admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      before_action :configure_permitted_parameters, if: :devise_controller?
      
#       def authorize_request(kind=nil)
#       unless kind.include?(:author)
#            redirect_to offers_path, notice:"You are not authorized perform this action"
#       end
# end
      def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role, :image])
            devise_parameter_sanitizer.permit(:account_update, keys: [:name,
            :image])
      end

      def show
                        
      end

      def user_params
            params.require(:user).permit!
      end

            
      


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ edit update destroy show]
  before_action :authenticate_user!, except: [:index,:show]
#   before_action only:[:new,:create,:edit,:update,:destroy] do
#   authorize_request[:admin]
#   end

  # GET /offers or /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1 or /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = current_user.offers.build
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = current_user.offers.build(offer_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully created." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url, notice: "Offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:description)
    end
end

app/controllers/postulants_controller.rb
class PostulantsController < ApplicationController
  before_action :set_postulant, only: %i[ show edit update destroy ]

  # GET /postulants or /postulants.json
  def index
    @postulants = Postulant.all
  end

  # GET /postulants/1 or /postulants/1.json
  def show
  end

  # GET /postulants/new
  def new
    @postulant = Postulant.new
  end

  # GET /postulants/1/edit
  def edit
  end

  # POST /postulants or /postulants.json
  def create
    @postulant = Postulant.new(postulant_params)

    respond_to do |format|
      if @postulant.save
        format.html { redirect_to postulant_url(@postulant), notice: "Postulant was successfully created." }
        format.json { render :show, status: :created, location: @postulant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @postulant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postulants/1 or /postulants/1.json
  def update
    respond_to do |format|
      if @postulant.update(postulant_params)
        format.html { redirect_to postulant_url(@postulant), notice: "Postulant was successfully updated." }
        format.json { render :show, status: :ok, location: @postulant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @postulant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postulants/1 or /postulants/1.json
  def destroy
    @postulant.destroy

    respond_to do |format|
      format.html { redirect_to postulants_url, notice: "Postulant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postulant
      @postulant = Postulant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def postulant_params
      params.require(:postulant).permit(:description, :message, :user_id, :offer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/postulants_helper.rb
module PostulantsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<%= link_to "New offer", new_offer_path %>
<%= link_to "New postulant", new_postulant_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Applaboral</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>

  <body>
      <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>  
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>    
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/_offer.html.erb
<div id="<%= dom_id offer %>">
  <p>
    <strong>Description:</strong>
    <%= offer.description %>
  </p>

</div>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render "form", offer: @offer %>

<br>

<div>
  <%= link_to "Show this offer", @offer %> |
  <%= link_to "Back to offers", offers_path %>
</div>

app/views/offers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Offers</h1>

<div id="offers">
  <% @offers.each do |offer| %>
    <%= render offer %>
    <p>
      <%= link_to "Show this offer", offer %>
    </p>
  <% end %>
</div>

<%= link_to "New offer", new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>
<%= render "form", offer: @offer %>
<%= link_to "Home", '/' %>
<br>

<div> 
  <%= link_to "Back to offers", offers_path %>
</div>

app/views/offers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @offer %>

<div>
  <%= link_to "Edit this offer", edit_offer_path(@offer) %> |
  <%= link_to "Back to offers", offers_path %>

  <%= button_to "Destroy this offer", @offer, method: :delete %>
</div>

app/views/postulants/_form.html.erb
<%= form_with(model: postulant) do |form| %>
  <% if postulant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(postulant.errors.count, "error") %> prohibited this postulant from being saved:</h2>

      <ul>
        <% postulant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :offer_id, style: "display: block" %>
    <%= form.text_field :offer_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/postulants/_postulant.html.erb
<div id="<%= dom_id postulant %>">
  <p>
    <strong>Description:</strong>
    <%= postulant.description %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= postulant.message %>
  </p>

  <p>
    <strong>User:</strong>
    <%= postulant.user_id %>
  </p>

  <p>
    <strong>Offer:</strong>
    <%= postulant.offer_id %>
  </p>

</div>

app/views/postulants/edit.html.erb
<h1>Editing postulant</h1>

<%= render "form", postulant: @postulant %>

<br>

<div>
  <%= link_to "Show this postulant", @postulant %> |
  <%= link_to "Back to postulants", postulants_path %>
</div>

app/views/postulants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Postulants</h1>

<div id="postulants">
  <% @postulants.each do |postulant| %>
    <%= render postulant %>
    <p>
      <%= link_to "Show this postulant", postulant %>
    </p>
  <% end %>
</div>

<%= link_to "New postulant", new_postulant_path %>

app/views/postulants/new.html.erb
<h1>New postulant</h1>

<%= render "form", postulant: @postulant %>

<br>

<div>
  <%= link_to "Back to postulants", postulants_path %>
</div>

app/views/postulants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @postulant %>

<div>
  <%= link_to "Edit this postulant", edit_postulant_path(@postulant) %> |
  <%= link_to "Back to postulants", postulants_path %>

  <%= button_to "Destroy this postulant", @postulant, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
  <% if user_signed_in? %>
  <% current_user.email %>
  <li class="nav-item nav-link">
  <%= current_user.email%>
  </li>
  <li>
        <%= link_to 'Home', '/' %>
  </li>
  <li>
      <%= link_to 'Ofertas', offers_path %>
  </li>
  <li>
      <%= link_to 'Postular', new_postulant_path %>
  </li>

  <li>
      <%= link_to 'Edita tus datos', edit_user_registration_path %>
  </li>
  <li>
      <%= button_to 'Cierre sesion', destroy_user_session_path, method: :delete %>
  </li>
  <%else%>
 
  <li>
      <%= link_to 'Inicia sesion', new_user_session_path %>
  </li>
  
  <li>
      <%= link_to 'Registrate', new_user_registration_path %>
  </li>
  </ul>
  <%end%>
  </div>
  </div>
  </nav>